In [ ]:
#Siddiqa Bagwan
#B24CE1093

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('netflix_titles.csv')

In [ ]:
df.head(3)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,added_year,added_month,added_day,type_encoded
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,unknown,United States,0.659930,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",0.116049,0.695053,1.273861,0
1,s2,TV Show,Blood & Water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,0.773324,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",0.116049,0.695053,1.172984,1
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,0.773324,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,0.116049,0.695053,1.172984,1

In [ ]:
df.tail(3)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,added_year,added_month,added_day,type_encoded
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,-0.587403,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,0.106605,1.269313,-1.147178,0
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,-0.927585,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",0.111327,-1.601989,-0.138412,0
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,0.092961,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,0.106605,-1.027729,-1.046302,0

In [ ]:
df.shape

(8807, 12)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [ ]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [ ]:
df.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [ ]:
df.fillna("unknown",axis=1,inplace=True)

In [ ]:
df.isna().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["date_added"] = pd.to_datetime(df["date_added"], errors="coerce")

In [ ]:
df["added_year"] = df["date_added"].dt.year
df["added_month"] = df["date_added"].dt.month
df["added_day"] = df["date_added"].dt.day

In [ ]:
df["added_year"] = df["added_year"].fillna(0).astype(int)
df["added_month"] = df["added_month"].fillna(0).astype(int)
df["added_day"] = df["added_day"].fillna(0).astype(int)

In [ ]:
df.drop("date_added", axis=1, inplace=True)

In [ ]:
df.head(3)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,added_year,added_month,added_day,type_encoded
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,unknown,United States,0.659930,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",0.116049,0.695053,1.273861,0
1,s2,TV Show,Blood & Water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,0.773324,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",0.116049,0.695053,1.172984,1
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,0.773324,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,0.116049,0.695053,1.172984,1

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
encoder = LabelEncoder()

df["type_encoded"] = encoder.fit_transform(df["type"])

In [ ]:
df.head(3)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,added_year,added_month,added_day,type_encoded
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,unknown,United States,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,9,25,0
1,s2,TV Show,Blood & Water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,9,24,1
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,9,24,1

In [ ]:
df_onehot = pd.get_dummies(df, columns=["rating"])

print(df_onehot.head())

  show_id     type                  title         director  \
0      s1    Movie   Dick Johnson Is Dead  Kirsten Johnson
1      s2  TV Show          Blood & Water          unknown
2      s3  TV Show              Ganglands  Julien Leclercq
3      s4  TV Show  Jailbirds New Orleans          unknown
4      s5  TV Show           Kota Factory          unknown

                                                cast        country  \
0                                            unknown  United States
1  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...   South Africa
2  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...        unknown
3                                            unknown        unknown
4  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...          India

  release_year   duration                                          listed_in  \
0         2020     90 min                                      Documentaries
1         2021  2 Seasons    International TV Shows, TV Dramas, TV Mysteries
2         2021   1 Season  Crime TV Shows, International TV Shows, TV Act...
3         2021   1 Season                             Docuseries, Reality TV
4         2021  2 Seasons  International TV Shows, Romantic TV Shows, TV ...

                                         description  ...  rating_R  \
0  As her father nears the end of his life, filmm...  ...     False
1  After crossing paths at a party, a Cape Town t...  ...     False
2  To protect his family from a powerful drug lor...  ...     False
3  Feuds, flirtations and toilet talk go down amo...  ...     False
4  In a city of coaching centers known to train I...  ...     False

   rating_TV-14  rating_TV-G  rating_TV-MA  rating_TV-PG  rating_TV-Y  \
0         False        False         False         False        False
1         False        False          True         False        False
2         False        False          True         False        False
3         False        False          True         False        False
4         False        False          True         False        False

   rating_TV-Y7  rating_TV-Y7-FV  rating_UR  rating_unknown
0         False            False      False           False
1         False            False      False           False
2         False            False      False           False
3         False            False      False           False
4         False            False      False           False

[5 rows x 32 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
scaler = MinMaxScaler()

cols = ["release_year", "added_year", "added_month", "added_day"]

df[cols] = scaler.fit_transform(df[cols])

In [ ]:
df.head(3)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,added_year,added_month,added_day,type_encoded
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,unknown,United States,0.659930,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",0.116049,0.695053,1.273861,0
1,s2,TV Show,Blood & Water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,0.773324,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",0.116049,0.695053,1.172984,1
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,0.773324,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,0.116049,0.695053,1.172984,1

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

cols = ["release_year", "added_year", "added_month", "added_day"]

df[cols] = scaler.fit_transform(df[cols])

In [ ]:
df.head(3)

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,added_year,added_month,added_day,type_encoded
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,unknown,United States,0.659930,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",0.116049,0.695053,1.273861,0
1,s2,TV Show,Blood & Water,unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,0.773324,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",0.116049,0.695053,1.172984,1
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",unknown,0.773324,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,0.116049,0.695053,1.172984,1